organization: "All-Weather Seal of West Michigan"
kpi_ranges:
  "Quality ranking":
    min: 7
    max: 10
  "Engagement rate ranking":
    min: 7
    max: 10
  "Conversion rate ranking":
    min: 7
    max: 10
  "CTR (link click-through rate)":
    min: 0.5
    max: 3
  "Unique CTR (link click-through rate)":
    min: 0.25
    max: 65
  "Cost per results":
    min: 1
    max: 30
  "Result rate":
    min: 0.1
    max: 3
  "CPM (cost per 1,000 impressions) (USD)":
    min: 1
    max: 20
  "CPC (cost per link click) (USD)":
    min: 0.01
    max: 3
  "Frequency":
    min: 1
    max: 8
  "Unique CTR (all)":
    min: 0.25
    max: 65
  "Link clicks":
    min: 1
    max: 10000
  "Leads":
    min: 1
    max: 10000
